### ISSUE TITLE
Weird release numbers

### ISSUE THREAD

**Issue by quintesse** [LaserWeb/LaserWeb4-Binaries#10]
Release numbers don't seem to coincide with the .exe you download? Also for the last several release the version of the downloaded .exe has stayed the same?

![image](https://user-images.githubusercontent.com/778793/37560035-02f41608-2a31-11e8-99a7-187ba2b8ad2b.png)

**Comment by jorgerobles** [comment]
Known issue. Since moved to new automated build, I could not get the
versions to be consecutive with the old build process.
Pull requests are welcome. :)

El 17 mar. 2018 22:17, "Tako Schotanus" <notifications@github.com> escribió:

Release numbers don't seem to coincide with the .exe you download? Also for
the last several release the version of the downloaded .exe has stayed the
same?

[image: image]
<https://user-images.githubusercontent.com/778793/37560035-02f41608-2a31-11e8-99a7-187ba2b8ad2b.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4-Binaries/issues/10>, or mute the
thread

**Comment by quintesse** [comment]
Sure, where's the build process defined?

And what _should_ be the correct numbering?

:)

**Comment by jorgerobles** [comment]
It's on appveyor and travis yml on this repository, the correct version
should be 4.0.1xxx.
127 fragment corresponds to lw.comm-server version.
